---
label: Project
hide_body: false
fields:
- type: text
  name: title
  label: title
- type: file
  name: thumbnail
  label: thumbnail
- type: text
  name: year
  label: year
- type: list
  name: categories
  label: categories
  config:
    use_select: false
- name: order
  type: number
  label: order
  description: sort order for appearance on the front page
  default: 0
  required: true
  config:
    min: 
    max: 
    step: 
pages:
- projects/the-london-book-fair.md
- projects/molecular-gastronomy.md
- projects/°-jupiter-calendar.md
